In [ ]:
mse
(H(x1) - y1)^2 + (H(x2) - y2)^2 + (H(x3) - y3)^2 / 3

In [25]:
from sklearn.datasets import load_digits
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
digits = load_digits()

In [3]:
type(digits)

sklearn.utils.Bunch

In [4]:
digits.keys() #Descr : 설명

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [5]:
digits.data[:1]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [8]:
digits.images[0] #원래 데이터, 숫자 0을 데이터화 한거임

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [9]:
digits.target[0]

0

In [15]:
digits.data[1010] #2차원 -> 1차원 데이터

array([ 0.,  0.,  9., 12., 12., 12.,  6.,  0.,  0.,  1., 14.,  6.,  4.,
        4.,  2.,  0.,  0.,  4., 15., 12.,  9.,  1.,  0.,  0.,  0.,  4.,
       15.,  8., 11., 11.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 14.,  4.,
        0.,  0.,  0.,  0.,  0.,  0., 10.,  8.,  0.,  0.,  0., 10.,  1.,
        0.,  8.,  8.,  0.,  0.,  0.,  9., 16., 16., 15.,  4.,  0.])

In [17]:
digits.data[1010].shape

(64,)

In [21]:
digits.data.shape #

(1797, 64)

In [22]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [23]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.bincount(digits.target) #개수(빈도수)세는 거 

array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180], dtype=int32)

In [40]:
digits.target.vlaue_counts()

AttributeError: 'numpy.ndarray' object has no attribute 'vlaue_counts'

In [48]:
X = digits.data 
y = digits.target
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = 0.2)

##  Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression

In [95]:
model = LogisticRegression(C = 0.0015)

In [96]:
model.fit(X_train, y_train)

C:\Users\163908\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\163908\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=0.0015, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
          solver='warn', tol=0.0001, verbose=0, warm_start=False)

In [97]:
model.predict(X_test)[:5]

array([2, 8, 2, 6, 6])

In [98]:
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))
#과대적합 -> 규제를 가해줘야함 C값을 낮춤

0.9659011830201809
0.9611111111111111


In [99]:
model.predict(X_test)[:5]

array([2, 8, 2, 6, 6])

In [104]:
model.predict_proba(X_test)[1] #확률이 높은게 선택

array([1.91200483e-03, 1.04297125e-02, 6.11741798e-02, 1.63607467e-04,
       7.74268613e-02, 2.01618240e-02, 2.33027257e-03, 1.27461464e-03,
       7.95809469e-01, 2.93174540e-02])

## SVM 

In [106]:
from sklearn.svm import LinearSVC

In [175]:
model = LinearSVC(C = 0.001)

In [176]:
model.fit(X_train, y_train)

LinearSVC(C=0.001, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [177]:
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

0.9819067501739736
0.9638888888888889


In [178]:
#분류
#회귀